version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api
    image: node:14
    working_dir: /app
    restart: always
    command: bash -c "npm install && npm run debug"
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    ports:
      - "3030:3030"
      - "9229:9229"
    links:
      - mongo
    environment:
      - "MONGO_URL=mongodb://mongo:27017/clean-node-api"
